/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Edge-Service API
 * Documentation Edge-Service API v1.0
 * OpenAPI spec version: 1.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export interface User {
  firstName?: string;
  lastName?: string;
  roles?: string[];
  username?: string;
}





  export const getUser = <TData = AxiosResponse<User>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/user`,options
    );
  }

export type GetUserResult = AxiosResponse<User>
